// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nektfxjfjhqhrcpigjjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5la3RmeGpmamhxaHJjcGlnamp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTgwMzUsImV4cCI6MjA2NjI5NDAzNX0.jYPA16o0FjLPDLDYPtqx_EruzmxNrA9Lsx9wYGCkIg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);